site_name: pyopia-gui
site_url: https://nimmo-smith-technologies.github.io/pyopia-gui/
repo_url: https://github.com/nimmo-smith-technologies/pyopia-gui
theme:
  name: material

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Using pyopia-gui: usage.md
  - Design decisions: decisions/INDEX.md
